name: Quality Gates

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok' --eval 'quit()'"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: ephemeral-test-db

    steps:
      - uses: actions/checkout@v4

      - name: Get Go version from go.mod
        id: get-go-version
        run: |
          go_version=$(grep -oP 'go \K[0-9\.]+' backend/go.mod)
          echo "GO_VERSION=$go_version" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install repository dependencies
        run: make install-repo-dependencies

      - name: Formatting validation
        run: make fmt-check

      - name: Test
        env:
          DB_URL: mongodb://root:ephemeral-test-db@localhost:27017/admin?authSource=admin
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_DEV_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_DEV_CLIENT_SECRET }}
        run: make test env=test

      - name: Configure Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # See https://github.com/Azure/login?tab=readme-ov-file#login-with-a-service-principal-secret

      - name: Lint validation
        run: make lint

      - name: Build
        run: make build

  dev-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # See https://github.com/Azure/login?tab=readme-ov-file#login-with-a-service-principal-secret

      - name: Terraform Apply
        run: make tf-apply-auto env=dev

      - name: Build and Push Docker Image
        run: |
          make build-image
          echo "${{ secrets.DOCKER_API_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          make push-image

      - name: Update Container App version
        run: |
          az containerapp update \
            --name tranquil-pages-dev-container-app \
            --resource-group tranquil-pages-dev-rg \
            --image docker.io/kjeldschmidt2/tranquil-pages:latest
