name: Quality Gates

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Go version from go.mod
        id: get-go-version
        run: |
          go_version=$(grep -oP 'go \K[0-9\.]+' go.mod)
          echo "GO_VERSION=$go_version" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod tidy

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Formatting validation
        run: make fmt-check

      - name: Lint validation
        run: make vet

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Configure Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # See https://github.com/Azure/login?tab=readme-ov-file#login-with-a-service-principal-secret

      - name: terraform validate
        run: make tf-validate

  dev-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # See https://github.com/Azure/login?tab=readme-ov-file#login-with-a-service-principal-secret

      - name: Terraform Apply
        run: make tf-apply-auto env=dev